webtalk_init -webtalk_dir E:/Github_Projects/Vivado_Projects/Easy_-_Parameterized_Synchronous_FIFO/Easy_-_Parameterized_Synchronous_FIFO.sim/sim_1/behav/xsim/xsim.dir/tb_sync_fifo_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 27 23:30:53 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4d843ad4-c0fa-4691-abdf-f11b072f2a61" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a85ec35a9b774e9e95b4f26b36859458" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12450H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "485 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10488_KB" -context "xsim\\usage"
webtalk_transmit -clientid 657589464 -regid "" -xml E:/Github_Projects/Vivado_Projects/Easy_-_Parameterized_Synchronous_FIFO/Easy_-_Parameterized_Synchronous_FIFO.sim/sim_1/behav/xsim/xsim.dir/tb_sync_fifo_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Github_Projects/Vivado_Projects/Easy_-_Parameterized_Synchronous_FIFO/Easy_-_Parameterized_Synchronous_FIFO.sim/sim_1/behav/xsim/xsim.dir/tb_sync_fifo_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Github_Projects/Vivado_Projects/Easy_-_Parameterized_Synchronous_FIFO/Easy_-_Parameterized_Synchronous_FIFO.sim/sim_1/behav/xsim/xsim.dir/tb_sync_fifo_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
